In [ ]:
# Hapus kunci instalasi lama dan masukkan yang baru dari Google
!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
!sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
!apt-get -y update
!apt-get install -y google-chrome-stable

# Pastikan webdriver-manager terinstal
!pip install webdriver-manager

Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 http://dl.google.com/linux/chrome/deb stable InRelease [1,825 B]
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:6 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,209 B]
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 6,951 B in 2s (3,794 B/s)
Reading package lists... Done
W: http://dl.google.com/linux/chrome/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libvulkan1 libxcomposite1 libxtst6
  mesa-vulkan-drivers session-migration
The following NEW packages will be installed:
  at-spi2-core google-chrome-stable gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libvulkan1
  libxcomposite1 libxtst6 mesa-vulkan-drivers session-migration
0 upgraded, 12 newly installed, 0 to remove and 7 not upgraded.
Need to get 139 MB of archives.
After this operation, 468 MB of additional disk space will be used.
Get:1 http://dl.google.com/linux/chrome/deb stable/main amd64 google-chrome-stable amd64 146.0.7680.164-1 [128 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvulkan1 amd64 1.3.204.1-2 [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mesa-vulkan-drivers amd64 23.2.1-1ubuntu3.1~22.04.3 [10.7 MB]
Fetched 139 MB in 4s (32.1 MB/s)
Selecting previously unselected package libatk1.0-data.
(Reading database ... 118709 files and directories currently installed.)
Preparing to unpack .../00-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../01-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatspi2.0-0:amd64.
Preparing to unpack .../02-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../03-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libvulkan1:amd64.
Preparing to unpack .../04-libvulkan1_1.3.204.1-2_amd64.deb ...
Unpacking libvulkan1:amd64 (1.3.204.1-2) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../05-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package google-chrome-stable.
Preparing to unpack .../06-google-chrome-stable_146.0.7680.164-1_amd64.deb ...
Unpacking google-chrome-stable (146.0.7680.164-1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../07-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../08-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../09-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../10-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package mesa-vulkan-drivers:amd64.
Preparing to unpack .../11-mesa-vulkan-drivers_23.2.1-1ubuntu3.1~22.04.3_amd64.deb ...
Unpacking mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up google-chrome-stable (146.0.7680.164-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...
Requirement already satisfied: webdriver-manager in /usr/local/lib/python3.12/dist-packages (4.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (26.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (2026.2.25)

In [ ]:
!pip install Sastrawi
!pip install selenium newspaper3k nltk Sastrawi webdriver-manager
!pip install lxml_html_clean

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (4.41.0)
Requirement already satisfied: newspaper3k in /usr/local/lib/python3.12/dist-packages (0.2.8)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: webdriver-manager in /usr/local/lib/python3.12/dist-packages (4.0.2)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (4.13.5)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (11.3.0)
Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.3)
Requirement already satisfied: cssselect>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (1.4.0)
Requirement already satisfied: lxml>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.2)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.32.4)
Requirement already satisfied: feedparser>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.12)
Requirement already satisfied: tldextract>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (5.3.1)
Requirement already satisfied: feedfinder2>=0.0.4 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (26.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8.3)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.12/dist-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.11)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.0.1)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.25.2)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: lxml_html_clean in /usr/local/lib/python3.12/dist-packages (0.4.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from lxml_html_clean) (6.0.2)

In [ ]:
import time
import os
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from newspaper import Article
import nltk
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
!apt-get update
!apt-get install -y google-chrome-stable

Hit:1 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (2,949 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
google-chrome-stable is already the newest version (146.0.7680.164-1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.

In [ ]:
!apt-get update
!apt-get install -y chromium-browser
!apt-get install -y chromium-chromedriver

Hit:1 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (2,699 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-browser is already the newest version (1:85.0.4183.83-0ubuntu2.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-chromedriver is already the newest version (1:85.0.4183.83-0ubuntu2.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.

In [ ]:
def get_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless") # Wajib berjalan di latar belakang
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")

    # Menonaktifkan pemuatan gambar agar proses scraping jauh lebih cepat
    prefs = {"profile.managed_default_content_settings.images": 2}
    chrome_options.add_experimental_option("prefs", prefs)

    # Biarkan webdriver-manager mencari Chrome asli yang baru kita instal
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=chrome_options)

    return driver

def extract_article_data(url):
    try:
        article = Article(url, language='id')
        article.download()
        article.parse()

        if len(article.text) < 200:
            return None

        return {
            "date_published": article.publish_date.strftime("%Y-%m-%d") if article.publish_date else None,
            "title": article.title,
            "content": article.text,
            "url": url
        }
    except Exception as e:
        return None

In [ ]:
# --- EKSEKUSI UTAMA ---
# TENTUKAN TANGGAL DI SINI (Format: YYYY-MM-DD)
start_date = "2021-01-01"
end_date = "2022-12-01"


date_range = pd.date_range(start=start_date, end=end_date).strftime("%Y/%m/%d").tolist()
print(f"Mulai scraping untuk {len(date_range)} hari...")

driver = get_driver()
nama_file_csv = "berita_mentah_cnbc.csv"

for date_str in date_range:
    print(f"\n--- Mengambil data untuk tanggal: {date_str} ---")
    url_indeks = f"https://www.cnbcindonesia.com/indeks?date={date_str}"

    try:
        driver.get(url_indeks)
        time.sleep(3)


        anchors = driver.find_elements("tag name", "a")
        links_hari_ini = []
        for a in anchors:
            href = a.get_attribute("href")
            if href and "/berita/" in href or "/market/" in href:
                if href.startswith("https") and href not in links_hari_ini:
                    links_hari_ini.append(href)

        print(f"Ditemukan {len(links_hari_ini)} link berita. Memulai ekstraksi...")


        data_hari_ini = []
        for i, link in enumerate(links_hari_ini[:20]):
            hasil = extract_article_data(link)
            if hasil:
                data_hari_ini.append(hasil)


        if data_hari_ini:
            df_hari_ini = pd.DataFrame(data_hari_ini)

            if not os.path.isfile(nama_file_csv):
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='w')
            else:
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='a', header=False)
            print(f" Berhasil menyimpan {len(data_hari_ini)} berita tanggal {date_str} ke CSV.")

    except Exception as e:
        print(f" Gagal memproses tanggal {date_str}: {e}")

driver.quit()
print(f"\nSelesai! Data aman di dalam file: {nama_file_csv}")

Mulai scraping untuk 700 hari...

--- Mengambil data untuk tanggal: 2021/01/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/01 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/02 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/01/03 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/03 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/04 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/01/05 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/05 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/06 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/06 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/07 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/07 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/08 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/01/08 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/09 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/09 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/10 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/01/11 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/11 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/12 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/01/12 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/13 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/13 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/01/14 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/15 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/15 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/16 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/01/17 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/01/17 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/18 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/01/19 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/01/19 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/01/20 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/21 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/21 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/22 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/01/22 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/01/23 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/24 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/01/25 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/01/25 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/26 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/01/26 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/27 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/01/27 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/28 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/01/28 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/29 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/01/29 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/30 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/01/30 ke CSV.

--- Mengambil data untuk tanggal: 2021/01/31 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/02/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/02/01 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/02 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/03 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/03 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/04 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/04 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/05 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/05 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/06 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/06 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/07 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/02/08 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/02/08 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/09 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/09 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/10 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/11 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/02/11 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/12 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/02/12 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/13 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/13 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/14 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/15 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/16 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/16 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/17 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/17 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/18 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/02/18 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/19 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/19 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/20 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/02/20 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/21 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/02/22 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/02/22 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/23 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/02/23 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/02/24 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/25 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/25 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/26 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/26 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/27 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/27 ke CSV.

--- Mengambil data untuk tanggal: 2021/02/28 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/02/28 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/01 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/02 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/03/02 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/03 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/03 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/04 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/05 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/03/05 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/06 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/06 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/07 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/07 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/08 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/03/08 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/09 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/09 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/10 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/10 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/11 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/12 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/12 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/13 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/13 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/14 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/03/15 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/03/15 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/16 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/16 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/17 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/17 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/18 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/18 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/19 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/19 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/20 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/21 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/21 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/22 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/03/22 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/23 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/24 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/03/24 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/25 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/25 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/26 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/26 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/27 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/27 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/28 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/28 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/29 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/29 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/03/30 ke CSV.

--- Mengambil data untuk tanggal: 2021/03/31 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/03/31 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/01 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/02 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/03 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/04/03 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/04 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/05 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/04/05 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/06 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/06 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/07 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/07 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/08 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/08 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/09 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/04/09 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/10 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/11 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/12 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/12 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/13 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/14 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/04/14 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/15 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/16 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/04/16 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/17 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/04/17 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/18 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/19 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/04/19 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/20 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/21 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/21 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/22 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/04/22 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/23 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/24 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/04/24 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/25 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/04/26 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/04/26 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/27 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/04/27 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/28 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/04/28 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/29 ---
Ditemukan 5 link berita. Memulai ekstraksi...
 Berhasil menyimpan 5 berita tanggal 2021/04/29 ke CSV.

--- Mengambil data untuk tanggal: 2021/04/30 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/04/30 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/01 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/05/01 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/02 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2021/05/03 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2021/05/03 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/05/04 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/05 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/05/05 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/06 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/05/06 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/07 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2021/05/07 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/08 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/05/08 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/09 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/05/09 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/05/10 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/11 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2021/05/11 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/12 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/05/12 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/05/13 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/05/14 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2021/05/15 ke CSV.

--- Mengambil data untuk tanggal: 2021/05/16 ---
Ditemukan 0 link berita. Memulai ekstraksi...


In [ ]:
# --- EKSEKUSI UTAMA ---
# TENTUKAN TANGGAL DI SINI (Format: YYYY-MM-DD)
start_date = "2022-12-01"
end_date = "2023-12-01"


date_range = pd.date_range(start=start_date, end=end_date).strftime("%Y/%m/%d").tolist()
print(f"Mulai scraping untuk {len(date_range)} hari...")

driver = get_driver()
nama_file_csv = "berita_mentah_cnbc.csv"

for date_str in date_range:
    print(f"\n--- Mengambil data untuk tanggal: {date_str} ---")
    url_indeks = f"https://www.cnbcindonesia.com/indeks?date={date_str}"

    try:
        driver.get(url_indeks)
        time.sleep(3)

        anchors = driver.find_elements("tag name", "a")
        links_hari_ini = []
        for a in anchors:
            href = a.get_attribute("href")
            if href and "/berita/" in href or "/market/" in href:
                if href.startswith("https") and href not in links_hari_ini:
                    links_hari_ini.append(href)

        print(f"Ditemukan {len(links_hari_ini)} link berita. Memulai ekstraksi...")

        data_hari_ini = []
        for i, link in enumerate(links_hari_ini[:20]):
            hasil = extract_article_data(link)
            if hasil:
                data_hari_ini.append(hasil)

        if data_hari_ini:
            df_hari_ini = pd.DataFrame(data_hari_ini)

            if not os.path.isfile(nama_file_csv):
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='w')
            else:
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='a', header=False)
            print(f" Berhasil menyimpan {len(data_hari_ini)} berita tanggal {date_str} ke CSV.")

    except Exception as e:
        print(f" Gagal memproses tanggal {date_str}: {e}")

driver.quit()
print(f"\nSelesai! Data aman di dalam file: {nama_file_csv}")

Mulai scraping untuk 366 hari...

--- Mengambil data untuk tanggal: 2022/12/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/01 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/02 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/03 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2022/12/04 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2022/12/04 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/05 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2022/12/05 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/06 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/06 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/07 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/07 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/08 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/08 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/09 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/09 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/10 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2022/12/11 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2022/12/12 ---
Ditemukan 5 link berita. Memulai ekstraksi...
 Berhasil menyimpan 5 berita tanggal 2022/12/12 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/13 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/14 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/15 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/16 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2022/12/16 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2022/12/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/18 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/19 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/19 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/20 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/21 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2022/12/21 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/22 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2022/12/22 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/23 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/24 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2022/12/25 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/25 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/26 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/26 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/27 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/27 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/28 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/28 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/29 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2022/12/29 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2022/12/30 ke CSV.

--- Mengambil data untuk tanggal: 2022/12/31 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/01/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/01/01 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/02 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/01/03 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/03 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/04 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/05 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2023/01/05 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/06 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/01/06 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/07 ---
Ditemukan 6 link berita. Memulai ekstraksi...
 Berhasil menyimpan 6 berita tanggal 2023/01/07 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/08 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/08 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/09 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/09 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/10 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/01/10 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/11 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/01/12 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/01/12 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/13 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/01/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/14 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/15 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/16 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/16 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/17 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/17 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/18 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/19 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/01/19 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/20 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/01/21 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/21 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/22 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/22 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/23 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2023/01/23 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/24 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/25 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/25 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/26 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2023/01/26 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/27 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/27 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/28 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/28 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/29 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/01/29 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/01/30 ke CSV.

--- Mengambil data untuk tanggal: 2023/01/31 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/01/31 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/02/01 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/02 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/03 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/03 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/04 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/02/04 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/05 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/06 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/06 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/07 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/07 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/08 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2023/02/08 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/09 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/09 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/10 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/11 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/12 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/13 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/14 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/15 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/16 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/16 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/18 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/19 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/02/19 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/20 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/21 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/21 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/22 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/22 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/23 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/02/23 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/24 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/25 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/02/26 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/02/26 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/27 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/27 ke CSV.

--- Mengambil data untuk tanggal: 2023/02/28 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/02/28 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/01 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/02 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/02 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/03 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/04 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/05 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/06 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/06 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/07 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/07 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/08 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/08 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/10 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/11 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/12 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/12 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/13 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/14 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/15 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/16 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/16 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/17 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/17 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/18 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/19 ---
Ditemukan 4 link berita. Memulai ekstraksi...
 Berhasil menyimpan 4 berita tanggal 2023/03/19 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/20 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/21 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/21 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/22 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/23 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/23 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/24 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/24 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/25 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/25 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/26 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/26 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/27 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/29 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/03/29 ke CSV.

--- Mengambil data untuk tanggal: 2023/03/30 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/03/31 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/03/31 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/01 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/04/02 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/04/02 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/03 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/04/03 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/04 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/05 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/05 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/06 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/04/07 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/04/08 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/04/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/04/10 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/04/10 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/11 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/12 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2023/04/12 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/13 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/14 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/15 ---
Ditemukan 3 link berita. Memulai ekstraksi...
 Berhasil menyimpan 3 berita tanggal 2023/04/15 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/16 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/16 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/04/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/18 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/19 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/19 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/20 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/04/20 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/21 ---
Ditemukan 1 link berita. Memulai ekstraksi...
 Berhasil menyimpan 1 berita tanggal 2023/04/21 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/22 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/04/23 ---
Ditemukan 2 link berita. Memulai ekstraksi...
 Berhasil menyimpan 2 berita tanggal 2023/04/23 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/24 ---
Ditemukan 5 link berita. Memulai ekstraksi...
 Berhasil menyimpan 5 berita tanggal 2023/04/24 ke CSV.

--- Mengambil data untuk tanggal: 2023/04/25 ---

In [ ]:
# --- EKSEKUSI UTAMA ---
# TENTUKAN TANGGAL DI SINI (Format: YYYY-MM-DD)
start_date = "2023-12-01"
end_date = "2024-12-01"


date_range = pd.date_range(start=start_date, end=end_date).strftime("%Y/%m/%d").tolist()
print(f"Mulai scraping untuk {len(date_range)} hari...")

driver = get_driver()
nama_file_csv = "berita_mentah_cnbc.csv"

for date_str in date_range:
    print(f"\n--- Mengambil data untuk tanggal: {date_str} ---")
    url_indeks = f"https://www.cnbcindonesia.com/indeks?date={date_str}"

    try:
        driver.get(url_indeks)
        time.sleep(3)

        anchors = driver.find_elements("tag name", "a")
        links_hari_ini = []
        for a in anchors:
            href = a.get_attribute("href")
            if href and "/berita/" in href or "/market/" in href:
                if href.startswith("https") and href not in links_hari_ini:
                    links_hari_ini.append(href)

        print(f"Ditemukan {len(links_hari_ini)} link berita. Memulai ekstraksi...")


        data_hari_ini = []
        for i, link in enumerate(links_hari_ini[:20]):
            hasil = extract_article_data(link)
            if hasil:
                data_hari_ini.append(hasil)

        if data_hari_ini:
            df_hari_ini = pd.DataFrame(data_hari_ini)

            if not os.path.isfile(nama_file_csv):
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='w')
            else:
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='a', header=False)
            print(f"Berhasil menyimpan {len(data_hari_ini)} berita tanggal {date_str} ke CSV.")

    except Exception as e:
        print(f" Gagal memproses tanggal {date_str}: {e}")

driver.quit()
print(f"\nSelesai! Data aman di dalam file: {nama_file_csv}")

Mulai scraping untuk 367 hari...

--- Mengambil data untuk tanggal: 2023/12/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2023/12/01 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/02 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2023/12/02 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/03 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/12/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/04 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/05 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/05 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/06 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/12/07 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2023/12/07 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/08 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/12/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/12/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/10 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/11 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/12 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2023/12/12 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/13 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/12/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/14 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/15 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2023/12/15 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/16 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2023/12/16 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/17 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2023/12/17 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/18 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/19 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/19 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/20 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/21 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2023/12/21 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/22 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/22 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/23 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/24 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/12/25 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/12/26 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/26 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/27 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/27 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/28 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2023/12/28 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/29 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2023/12/29 ke CSV.

--- Mengambil data untuk tanggal: 2023/12/30 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2023/12/31 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2023/12/31 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/01 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/02 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/03 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/03 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/04 ---
Ditemukan 4 link berita. Memulai ekstraksi...
Berhasil menyimpan 4 berita tanggal 2024/01/04 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/05 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/05 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/06 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/07 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/08 ---
Ditemukan 4 link berita. Memulai ekstraksi...
Berhasil menyimpan 4 berita tanggal 2024/01/08 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/09 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/01/09 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/10 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/11 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/12 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/12 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/13 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/14 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/15 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/16 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/16 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/17 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/17 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/18 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/19 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/20 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/21 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/22 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/22 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/23 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/01/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/24 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/25 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/01/25 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/26 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/26 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/27 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/27 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/28 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/01/28 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/29 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/29 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/30 ke CSV.

--- Mengambil data untuk tanggal: 2024/01/31 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/01/31 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/01 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2024/02/01 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/02 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/03 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/02/03 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/04 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/05 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/02/05 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/06 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/02/06 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/07 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/02/07 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/08 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/02/08 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/10 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/11 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/12 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/13 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/02/13 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/14 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/15 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/16 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/18 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/19 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/20 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/21 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/21 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/22 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/22 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/23 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/24 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/02/25 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/02/25 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/26 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/26 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/27 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/02/27 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/28 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/28 ke CSV.

--- Mengambil data untuk tanggal: 2024/02/29 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/02/29 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/01 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/02 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/03 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/04 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/03/04 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/05 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/06 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/06 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/07 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/08 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/03/08 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/10 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/11 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/12 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/03/12 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/13 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/14 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/15 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/16 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/18 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/19 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/03/19 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/20 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/21 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/03/21 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/22 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/03/22 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/23 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/24 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/25 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/25 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/26 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/03/26 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/27 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/27 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/03/29 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/29 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/03/30 ke CSV.

--- Mengambil data untuk tanggal: 2024/03/31 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2024/03/31 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/01 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2024/04/01 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/04/02 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/03 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/04 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2024/04/04 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/05 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/04/05 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/06 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/07 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/08 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/04/08 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/04/10 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/11 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/12 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/04/13 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/14 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/15 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/04/15 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/16 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/04/16 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/17 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/04/17 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/04/18 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/19 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/04/19 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/20 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/21 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/22 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/04/22 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/23 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2024/04/23 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/04/24 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/25 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/04/25 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/26 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/04/26 ke CSV.

--- Mengambil data untuk tanggal: 2024/04/27 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/04/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...


In [ ]:
# --- EKSEKUSI UTAMA ---
# TENTUKAN TANGGAL DI SINI (Format: YYYY-MM-DD)
start_date = "2024-12-01"
end_date = "2025-12-01"


date_range = pd.date_range(start=start_date, end=end_date).strftime("%Y/%m/%d").tolist()
print(f"Mulai scraping untuk {len(date_range)} hari...")

driver = get_driver()
nama_file_csv = "berita_mentah_cnbc.csv"

for date_str in date_range:
    print(f"\n--- Mengambil data untuk tanggal: {date_str} ---")
    url_indeks = f"https://www.cnbcindonesia.com/indeks?date={date_str}"

    try:
        driver.get(url_indeks)
        time.sleep(3)


        anchors = driver.find_elements("tag name", "a")
        links_hari_ini = []
        for a in anchors:
            href = a.get_attribute("href")
            if href and "/berita/" in href or "/market/" in href:
                if href.startswith("https") and href not in links_hari_ini:
                    links_hari_ini.append(href)

        print(f"Ditemukan {len(links_hari_ini)} link berita. Memulai ekstraksi...")


        data_hari_ini = []
        for i, link in enumerate(links_hari_ini[:20]):
            hasil = extract_article_data(link)
            if hasil:
                data_hari_ini.append(hasil)


        if data_hari_ini:
            df_hari_ini = pd.DataFrame(data_hari_ini)

            if not os.path.isfile(nama_file_csv):
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='w')
            else:
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='a', header=False)
            print(f"Berhasil menyimpan {len(data_hari_ini)} berita tanggal {date_str} ke CSV.")

    except Exception as e:
        print(f"Gagal memproses tanggal {date_str}: {e}")

driver.quit()
print(f"\nSelesai! Data aman di dalam file: {nama_file_csv}")

Mulai scraping untuk 366 hari...

--- Mengambil data untuk tanggal: 2024/12/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/01 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/02 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/03 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/03 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/04 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/05 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/05 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/06 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/12/07 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2024/12/07 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/08 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/08 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/09 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/09 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/10 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/11 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/12/12 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/12 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/13 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/13 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/14 ---
Ditemukan 4 link berita. Memulai ekstraksi...
Berhasil menyimpan 4 berita tanggal 2024/12/14 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/15 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/12/16 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/12/17 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/17 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/18 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/19 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/19 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/20 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/12/21 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/21 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/22 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/22 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/23 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/24 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/25 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/25 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/26 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/26 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/27 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/12/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/12/29 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2024/12/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2024/12/30 ke CSV.

--- Mengambil data untuk tanggal: 2024/12/31 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2024/12/31 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/01/01 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/02 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/03 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/03 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/04 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/01/04 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/05 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/05 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/06 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/06 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/07 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/07 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/08 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/01/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/01/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/10 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/11 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/12 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/12 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/13 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/14 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/01/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/15 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/16 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/16 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/01/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/18 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/19 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2025/01/19 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/20 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/01/21 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/21 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/22 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/01/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/23 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/24 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/25 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/01/25 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/26 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/01/27 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/27 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/01/29 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2025/01/29 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/30 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2025/01/30 ke CSV.

--- Mengambil data untuk tanggal: 2025/01/31 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/01/31 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/01 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/02 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/02/02 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/03 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/03 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/04 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/05 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/05 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/06 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/02/06 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/07 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/07 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/08 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/09 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/02/09 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/10 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/11 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2025/02/11 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/12 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/13 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/14 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/15 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/02/15 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/16 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/17 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/17 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/18 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/19 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/02/19 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/20 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/21 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/22 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/02/22 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/02/23 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/24 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/25 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/26 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/02/26 ke CSV.

--- Mengambil data untuk tanggal: 2025/02/27 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/02/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/01 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/02 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/03 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/04 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/05 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/06 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/07 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/07 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/08 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/08 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/09 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/09 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/10 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/11 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/12 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/13 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/14 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/03/14 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/15 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/16 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2025/03/16 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/18 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/19 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/19 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/20 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/21 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/22 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/23 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/24 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/25 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/26 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/27 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/29 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/03/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/03/30 ke CSV.

--- Mengambil data untuk tanggal: 2025/03/31 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/01 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/02 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/03 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/03 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/04 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/05 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/06 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/04/06 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/07 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2025/04/07 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/08 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/08 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/09 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/04/09 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/10 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/11 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/12 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2025/04/12 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/13 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/04/13 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/14 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/15 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/16 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/18 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/04/18 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/19 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/20 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/21 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/22 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/23 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/24 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/25 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/26 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/27 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2025/04/27 ke CSV.

--- Mengambil data untuk tanggal: 2025/04/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/29 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/04/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/04/30 ke CSV.

--- Mengambil data untuk tanggal: 2025/05/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/05/01 ke CSV.

--- Mengambil data untuk tanggal: 2025/05/02 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/05/03 ---

In [ ]:

# TENTUKAN TANGGAL DI SINI (Format: YYYY-MM-DD)
start_date = "2025-12-01"
end_date = "2026-3-01" # Coba 1 minggu dulu sebagai tes

# Membuat daftar tanggal
date_range = pd.date_range(start=start_date, end=end_date).strftime("%Y/%m/%d").tolist()
print(f"Mulai scraping untuk {len(date_range)} hari...")

driver = get_driver()
nama_file_csv = "berita_mentah_cnbc.csv"

for date_str in date_range:
    print(f"\n--- Mengambil data untuk tanggal: {date_str} ---")
    url_indeks = f"https://www.cnbcindonesia.com/indeks?date={date_str}"

    try:
        driver.get(url_indeks)
        time.sleep(3) # Tunggu loading halaman

        # Kumpulkan link berita
        anchors = driver.find_elements("tag name", "a")
        links_hari_ini = []
        for a in anchors:
            href = a.get_attribute("href")
            if href and "/berita/" in href or "/market/" in href:
                if href.startswith("https") and href not in links_hari_ini:
                    links_hari_ini.append(href)

        print(f"Ditemukan {len(links_hari_ini)} link berita. Memulai ekstraksi...")

        # Proses setiap artikel di hari tersebut
        data_hari_ini = []
        for i, link in enumerate(links_hari_ini[:20]): # Opsional: Batasi 20 berita per hari agar cepat
            hasil = extract_article_data(link)
            if hasil:
                data_hari_ini.append(hasil)

        # AUTO-SAVE: Langsung simpan ke CSV setiap selesai 1 hari!
        if data_hari_ini:
            df_hari_ini = pd.DataFrame(data_hari_ini)
            # Jika file belum ada, buat baru dengan header. Jika sudah ada, tambahkan datanya di bawah (append)
            if not os.path.isfile(nama_file_csv):
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='w')
            else:
                df_hari_ini.to_csv(nama_file_csv, index=False, mode='a', header=False)
            print(f"Berhasil menyimpan {len(data_hari_ini)} berita tanggal {date_str} ke CSV.")

    except Exception as e:
        print(f"Gagal memproses tanggal {date_str}: {e}")

driver.quit()
print(f"\nSelesai! Data aman di dalam file: {nama_file_csv}")

Mulai scraping untuk 91 hari...

--- Mengambil data untuk tanggal: 2025/12/01 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/02 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/03 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/12/03 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/04 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/04 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/05 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/06 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/06 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/07 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/12/07 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/08 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/10 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/11 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/12 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/12 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/13 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/14 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/15 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/16 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/16 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/17 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/18 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/19 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/19 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/20 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/21 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/12/21 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/22 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/23 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/24 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/25 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/25 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/26 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/27 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2025/12/27 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/29 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2025/12/29 ke CSV.

--- Mengambil data untuk tanggal: 2025/12/30 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2025/12/31 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/01 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/02 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/03 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/04 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2026/01/04 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/05 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/06 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/07 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/08 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/08 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/09 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/09 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/10 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2026/01/10 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/11 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2026/01/11 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/12 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/13 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/14 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/15 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/16 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/17 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/17 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/18 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/19 ---
Ditemukan 4 link berita. Memulai ekstraksi...
Berhasil menyimpan 4 berita tanggal 2026/01/19 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/20 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/21 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2026/01/21 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/22 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/22 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/23 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/24 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/24 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/25 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/25 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/26 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/27 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/28 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/01/29 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2026/01/29 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/30 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/30 ke CSV.

--- Mengambil data untuk tanggal: 2026/01/31 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/01/31 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/01 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/01 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/02 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/02 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/03 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/04 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/05 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/05 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/06 ---
Ditemukan 3 link berita. Memulai ekstraksi...
Berhasil menyimpan 3 berita tanggal 2026/02/06 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/07 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2026/02/07 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/08 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/08 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/09 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/10 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/10 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/11 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/11 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/12 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/13 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/13 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/14 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/14 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/15 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/15 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/16 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2026/02/16 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/17 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2026/02/17 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/18 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/18 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/19 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/20 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/20 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/21 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/21 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/22 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/23 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/23 ke CSV.

--- Mengambil data untuk tanggal: 2026/02/24 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/25 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/26 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/27 ---
Ditemukan 0 link berita. Memulai ekstraksi...

--- Mengambil data untuk tanggal: 2026/02/28 ---
Ditemukan 1 link berita. Memulai ekstraksi...
Berhasil menyimpan 1 berita tanggal 2026/02/28 ke CSV.

--- Mengambil data untuk tanggal: 2026/03/01 ---
Ditemukan 2 link berita. Memulai ekstraksi...
Berhasil menyimpan 2 berita tanggal 2026/03/01 ke CSV.

Selesai! Data aman di dalam file: berita_mentah_cnbc.csv

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')

print("Memuat data dari CSV...")

df_berita = pd.read_csv("berita_mentah_cnbc.csv")

df_berita = df_berita.dropna(subset=['date_published'])
print(f"Total berita yang akan diproses: {len(df_berita)} artikel")


factory = StemmerFactory()
stemmer = factory.create_stemmer()

def bersihkan_teks(teks):
    if not isinstance(teks, str):
        return ""

    tokens = word_tokenize(teks)

    teks_bersih = " ".join(tokens)
    return stemmer.stem(teks_bersih)

print("Memulai proses Stemming Sastrawi (Ini mungkin memakan waktu)...")

df_sample = df_berita.head(5).copy()

df_sample['content_clean'] = df_sample['content'].apply(bersihkan_teks)

print("\nHasil Preprocessing:")
print(df_sample[['title', 'content_clean']])

df_berita['content_clean'] = df_berita['content'].apply(bersihkan_teks)
df_berita.to_csv("berita_bersih_sastrawi.csv", index=False)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Memuat data dari CSV...
Total berita yang akan diproses: 2286 artikel
Memulai proses Stemming Sastrawi (Ini mungkin memakan waktu)...

Hasil Preprocessing:
                                               title  \
0           Awas Bubble! Saham Tesla Sudah Kemahalan
1  Emas Boleh Cuan 25%, Tapi Ada yang Lebih 'Gila...
2  Sederet Faktor yang Membuat BRI Optimis Songso...
3  BTN Guyur Subsidi Bunga KPR Rp 2,49 T Hingga A...
4  Senat Diprediksi Tetap Sehat, Wall Street Dibu...

                                       content_clean
0  jakarta cnbc indonesia - saham emiten mobil li...
1  jakarta cnbc indonesia - emas memang jadi sala...
2  jakarta cnbc indonesia - pt bank rakyat indone...
3  jakarta cnbc indonesia - pt bank tabung negara...
4  jakarta cnbc indonesia - bursa saham amerika s...

In [ ]:


# Muat data berita mentah
df_mentah = pd.read_csv('berita_mentah_cnbc.csv')

print("\n--- Data Berita Mentah (Raw Data) ---")
display(df_mentah.head())
print("\nDeskripsi Statistik Data Mentah:")
display(df_mentah.describe(include='all'))

--- Data Berita Mentah (Raw Data) ---

,date_published,title,content,url
0,2021-01-01,Awas Bubble! Saham Tesla Sudah Kemahalan,"Jakarta, CNBC Indonesia - Saham emiten mobil l...",https://www.cnbcindonesia.com/market/202101011...
1,2021-01-01,"Emas Boleh Cuan 25%, Tapi Ada yang Lebih 'Gila...","Jakarta, CNBC Indonesia - Emas memang menjadi ...",https://www.cnbcindonesia.com/market/202101011...
2,2021-01-03,Sederet Faktor yang Membuat BRI Optimis Songso...,"Jakarta, CNBC Indonesia - PT. Bank Rakyat Indo...",https://www.cnbcindonesia.com/market/202101032...
3,2021-01-03,"BTN Guyur Subsidi Bunga KPR Rp 2,49 T Hingga A...","Jakarta, CNBC Indonesia - PT Bank Tabungan Neg...",https://www.cnbcindonesia.com/market/202101031...
4,2021-01-05,"Senat Diprediksi Tetap Sehat, Wall Street Dibu...","Jakarta, CNBC Indonesia - Bursa saham Amerika ...",https://www.cnbcindonesia.com/market/202101052...

Deskripsi Statistik Data Mentah:

,date_published,title,content,url
count,2286,2286,2286,2286
unique,1359,2273,2281,2282
top,2023-07-25,"Tertarik Punya Alfamart Sendiri, Segini Biaya ...","Jakarta, CNBC Indonesia - Bursa saham Amerika ...",https://www.cnbcindonesia.com/market/202212012...
freq,8,3,2,2

In [ ]:
# Muat data berita yang sudah dibersihkan
df_bersih = pd.read_csv('berita_bersih_sastrawi.csv')

print("\n--- Data Berita yang Sudah Dibersihkan (Cleaned Data) ---")
display(df_bersih.head())
print("\nDeskripsi Statistik Data Bersih:")
display(df_bersih.describe(include='all'))

--- Data Berita yang Sudah Dibersihkan (Cleaned Data) ---

,date_published,title,content,url,content_clean
0,2021-01-01,Awas Bubble! Saham Tesla Sudah Kemahalan,"Jakarta, CNBC Indonesia - Saham emiten mobil l...",https://www.cnbcindonesia.com/market/202101011...,jakarta cnbc indonesia - saham emiten mobil li...
1,2021-01-01,"Emas Boleh Cuan 25%, Tapi Ada yang Lebih 'Gila...","Jakarta, CNBC Indonesia - Emas memang menjadi ...",https://www.cnbcindonesia.com/market/202101011...,jakarta cnbc indonesia - emas memang jadi sala...
2,2021-01-03,Sederet Faktor yang Membuat BRI Optimis Songso...,"Jakarta, CNBC Indonesia - PT. Bank Rakyat Indo...",https://www.cnbcindonesia.com/market/202101032...,jakarta cnbc indonesia - pt bank rakyat indone...
3,2021-01-03,"BTN Guyur Subsidi Bunga KPR Rp 2,49 T Hingga A...","Jakarta, CNBC Indonesia - PT Bank Tabungan Neg...",https://www.cnbcindonesia.com/market/202101031...,jakarta cnbc indonesia - pt bank tabung negara...
4,2021-01-05,"Senat Diprediksi Tetap Sehat, Wall Street Dibu...","Jakarta, CNBC Indonesia - Bursa saham Amerika ...",https://www.cnbcindonesia.com/market/202101052...,jakarta cnbc indonesia - bursa saham amerika s...

Deskripsi Statistik Data Bersih:

,date_published,title,content,url,content_clean
count,2286,2286,2286,2286,2286
unique,1359,2273,2281,2282,2281
top,2023-07-25,"Tertarik Punya Alfamart Sendiri, Segini Biaya ...","Jakarta, CNBC Indonesia - Bursa saham Amerika ...",https://www.cnbcindonesia.com/market/202212012...,jakarta cnbc indonesia - bursa saham amerika s...
freq,8,3,2,2,2

In [ ]:
print("\n--- Perbandingan Konten (Mentah vs Bersih) ---")
# Ambil beberapa sampel untuk perbandingan
comparison_df = df_mentah[['title', 'content']].head(5).copy()
comparison_df['content_clean'] = df_bersih['content_clean'].head(5)
display(comparison_df[['title', 'content', 'content_clean']])

--- Perbandingan Konten (Mentah vs Bersih) ---

,title,content,content_clean
0,Awas Bubble! Saham Tesla Sudah Kemahalan,"Jakarta, CNBC Indonesia - Saham emiten mobil l...",jakarta cnbc indonesia - saham emiten mobil li...
1,"Emas Boleh Cuan 25%, Tapi Ada yang Lebih 'Gila...","Jakarta, CNBC Indonesia - Emas memang menjadi ...",jakarta cnbc indonesia - emas memang jadi sala...
2,Sederet Faktor yang Membuat BRI Optimis Songso...,"Jakarta, CNBC Indonesia - PT. Bank Rakyat Indo...",jakarta cnbc indonesia - pt bank rakyat indone...
3,"BTN Guyur Subsidi Bunga KPR Rp 2,49 T Hingga A...","Jakarta, CNBC Indonesia - PT Bank Tabungan Neg...",jakarta cnbc indonesia - pt bank tabung negara...
4,"Senat Diprediksi Tetap Sehat, Wall Street Dibu...","Jakarta, CNBC Indonesia - Bursa saham Amerika ...",jakarta cnbc indonesia - bursa saham amerika s...